name: Generate Release Notes

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grant write permissions to GITHUB_TOKEN

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history and branches are fetched

      - name: Set up environment variables
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Generate Release Notes
        run: |
          RELEASE_BRANCH="release/daily/$TODAY"
          RETENTION_BRANCH="release-retention/daily/$TODAY"
          ACTIVATION_BRANCH="release-activation/daily/$TODAY"

          NOTES="## Changes in this release\n\n"

          get_commits() {
            local branch=$1
            if git show-ref --quiet refs/remotes/origin/$branch; then
              local base=$(git merge-base main origin/$branch)
              local commits=$(git log $base..origin/$branch --oneline)
              if [[ ! -z "$commits" ]]; then
                NOTES+="### ${branch}\n"
                while IFS= read -r line; do
                  NOTES+="- $line\n"
                done <<< "$commits"
                NOTES+="\n"
              fi
            fi
          }

          get_commits "$RETENTION_BRANCH"
          get_commits "$ACTIVATION_BRANCH"

          echo -e "$NOTES" | tee -a CHANGELOG.md

      - name: Commit and Push CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add CHANGELOG.md
          git commit -m "Update release notes for $TODAY" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
