name: Generate and Publish Release Notes

permissions:
  contents: write  # Grants write access to repository contents
  pull-requests: write  # Grants write access to pull requests
  actions: write  # Grants permissions to create releases

on:
  push:
    branches:
      - main  # Trigger when a release branch is merged into main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate Release Notes
        run: |
          echo "## Release Notes for $(date)" > release-notes.md

          # Get all commits from release branches to debug the commit messages
          echo "### All Commits (for Debugging)" >> release-notes.md
          git log --oneline release/daily/* >> release-notes.md

          # Show the file content for debugging
          cat release-notes.md

      - name: Commit Release Notes
        run: |
          git add release-notes.md
          git commit -m "Update release notes"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      - name: Create Tag for Release
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Tag with current date
          echo "Creating tag $TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}  # Use the tag created earlier
          files: release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
