name: Generate Release Notes

permissions:
  contents: write  # Grants write access to repository contents

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate Release Notes
        run: |
          echo "## Release Notes for $(date)" > release-notes.md
          echo "### Retention Team" >> release-notes.md
          git log --oneline --no-merges release-retention/daily/* >> retention-commits.txt
          cat retention-commits.txt >> release-notes.md
          echo "### Activation Team" >> release-notes.md
          git log --oneline --no-merges release-activation/daily/* >> activation-commits.txt
          cat activation-commits.txt >> release-notes.md
          echo "### Nek Team" >> release-notes.md
          git log --oneline --no-merges release-nek/daily/* >> nek-commits.txt
          cat nek-commits.txt >> release-notes.md

      - name: Commit and Push Release Notes
        run: |
          git add release-notes.md
          git commit -m "Update release notes"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Naresh-Srinivas/hello-hello-world-git-actions.git HEAD:main
