name: Create Release on Merge

on:
  push:
    branches:
      - main  # Trigger when code is merged into `main`

jobs:
  release:
    permissions:
      contents: write  # Required to publish the release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Generate release version
        id: version
        run: echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: notes
        run: |
          echo "NOTES=$(git log --pretty=format:'- %s' -n 10 | sed ':a;N;$!ba;s/\n/\\n/g')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            ## Changes in this release
            ${{ env.NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG
        run: |
          echo "## Release ${{ env.VERSION }}" >> CHANGELOG.md
          echo "${{ env.NOTES }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "Update changelog for ${{ env.VERSION }}"
          git push origin main
