name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Fetch All Branches
        run: git fetch --prune --all

      - name: Detect Latest Release Date
        run: |
          # Get the latest release branch (e.g. release/daily/2025-02-02)
          RELEASE_BRANCH=$(git branch -r --sort=-committerdate | grep "release/daily" | head -n 1 | sed 's/origin\///' | awk '{$1=$1};1')
          RELEASE_DATE=$(echo "$RELEASE_BRANCH" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}")
          
          echo "Detected Release Branch: $RELEASE_BRANCH"
          echo "Detected Release Date: $RELEASE_DATE"
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Get Team Branches & Generate Release Notes
        run: |
          RETENTION_BRANCH="origin/release-retention/daily/$RELEASE_DATE"
          ACTIVATION_BRANCH="origin/release-activation/daily/$RELEASE_DATE"
          
          echo "## Changes in this release" > release_notes.md
          echo "" >> release_notes.md
          
          echo "### Activation Team" >> release_notes.md
          if git ls-remote --exit-code origin "release-activation/daily/$RELEASE_DATE" >/dev/null; then
            git log --oneline --no-merges $ACTIVATION_BRANCH >> release_notes.md
          else
            echo "No commits for Activation Team." >> release_notes.md
          fi
          
          echo "" >> release_notes.md
          echo "### Retention Team" >> release_notes.md
          if git ls-remote --exit-code origin "release-retention/daily/$RELEASE_DATE" >/dev/null; then
            git log --oneline --no-merges $RETENTION_BRANCH >> release_notes.md
          else
            echo "No commits for Retention Team." >> release_notes.md
          fi
          
          cat release_notes.md

      - name: Upload Release Notes as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes.md
