name: Generate and Publish Release Notes

permissions:
  contents: write  # Grants write access to repository contents
  pull-requests: write  # Grants write access to pull requests
  actions: write  # Grants permissions to create releases

on:
  push:
    branches:
      - main  # This will run when a release branch is merged into main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate Release Notes
        run: |
          echo "## Release Notes for $(date)" > release-notes.md
          
          # For Retention Team
          echo "### Retention Team" >> release-notes.md
          git log --oneline --no-merges "release-retention/daily/*" >> release-notes.md
          
          # For Activation Team
          echo "### Activation Team" >> release-notes.md
          git log --oneline --no-merges "release-activation/daily/*" >> release-notes.md
          
          # For Nek Team
          echo "### Nek Team" >> release-notes.md
          git log --oneline --no-merges "release-nek/daily/*" >> release-notes.md

      - name: Commit Release Notes
        run: |
          git add release-notes.md
          git commit -m "Update release notes"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Naresh-Srinivas/hello-hello-world-git-actions.git HEAD:main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

