name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Generate Release Notes
        run: |
          TODAY=$(date +'%Y-%m-%d')
          RELEASE_BRANCH="origin/release/daily/$TODAY"
          ACTIVATION_BRANCH="origin/release-activation/daily/$TODAY"
          RETENTION_BRANCH="origin/release-retention/daily/$TODAY"

          RELEASE_NOTES="## Changes in this release\n\n"

          get_commits() {
            local branch=$1
            if git ls-remote --exit-code --heads origin "$branch" &> /dev/null; then
              BASE=$(git merge-base origin/main $branch)
              COMMITS=$(git log --oneline --no-merges $BASE..$branch)
              if [[ ! -z "$COMMITS" ]]; then
                RELEASE_NOTES+="### $(basename $branch)\n$COMMITS\n\n"
              fi
            else
              echo "Branch $branch not found. Skipping..."
            fi
          }

          get_commits "$ACTIVATION_BRANCH"
          get_commits "$RETENTION_BRANCH"

          echo -e "$RELEASE_NOTES" > RELEASE_NOTES.md
          cat RELEASE_NOTES.md

      - name: Commit and Push Changes
        run: |
          git add RELEASE_NOTES.md
          git commit -m "Update release notes for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "No changes to push"
