name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Identify Latest Release Date
        run: |
          RELEASE_BRANCH=$(git branch -r --sort=-committerdate | grep "release/daily" | head -n 1 | sed 's/origin\///' | awk '{$1=$1};1')
          RELEASE_DATE=$(echo "$RELEASE_BRANCH" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}")

          echo "Detected Release Date: $RELEASE_DATE"
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Get Team Branches
        run: |
          RETENTION_BRANCH="origin/release-retention/daily/$RELEASE_DATE"
          ACTIVATION_BRANCH="origin/release-activation/daily/$RELEASE_DATE"

          echo "Checking branches: $RETENTION_BRANCH and $ACTIVATION_BRANCH"

          echo "RETENTION_BRANCH=$RETENTION_BRANCH" >> $GITHUB_ENV
          echo "ACTIVATION_BRANCH=$ACTIVATION_BRANCH" >> $GITHUB_ENV

      - name: Generate Release Notes
        run: |
          echo "## Changes in this release" > release_notes.md

          echo -e "\n### Activation Team" >> release_notes.md
          ACT_COMMITS=$(git log --oneline --no-merges $ACTIVATION_BRANCH || echo "No commits for today.")
          echo -e "$ACT_COMMITS" >> release_notes.md

          echo -e "\n### Retention Team" >> release_notes.md
          RET_COMMITS=$(git log --oneline --no-merges $RETENTION_BRANCH || echo "No commits for today.")
          echo -e "$RET_COMMITS" >> release_notes.md

      - name: Upload Release Notes as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes.md
