name: Generate Release Notes

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Runs when release branch is merged to main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we have the full history

      - name: Detect Release Branch & Date
        run: |
          # Find latest merged release branch into main
          RELEASE_BRANCH=$(git log --merges --oneline origin/main | grep "Merge pull request" | grep "release/daily" | head -n 1 | awk '{print $NF}')
          
          # Extract the release date from the branch name
          RELEASE_DATE=$(echo "$RELEASE_BRANCH" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}")
          
          echo "Detected Release Branch: $RELEASE_BRANCH"
          echo "Detected Release Date: $RELEASE_DATE"

          # Export environment variables
          echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Get Latest Merge Commit
        run: |
          MERGE_COMMIT=$(git log --oneline --merges origin/$RELEASE_BRANCH | grep "Merge pull request" | head -n 1 | awk '{print $1}')
          echo "MERGE_COMMIT=$MERGE_COMMIT" >> $GITHUB_ENV
          echo "Latest Merge Commit: $MERGE_COMMIT"

      - name: Get Team Branches & Commits
        run: |
          # Define retention and activation branches
          RETENTION_BRANCH="release-retention/daily/$RELEASE_DATE"
          ACTIVATION_BRANCH="release-activation/daily/$RELEASE_DATE"

          echo "Checking branches: $RETENTION_BRANCH and $ACTIVATION_BRANCH"

          # Create the release notes file
          echo "## Changes in this release" > release_notes.md

          # Fetch Activation Team commits
          echo -e "\n### Activation Team" >> release_notes.md
          ACT_COMMITS=$(git log --oneline origin/$ACTIVATION_BRANCH..origin/$RELEASE_BRANCH || echo "No commits for today.")
          echo -e "$ACT_COMMITS" >> release_notes.md

          # Fetch Retention Team commits
          echo -e "\n### Retention Team" >> release_notes.md
          RET_COMMITS=$(git log --oneline origin/$RETENTION_BRANCH..origin/$RELEASE_BRANCH || echo "No commits for today.")
          echo -e "$RET_COMMITS" >> release_notes.md

      - name: Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes.md
