name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get full commit history

      - name: Set release date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get new commits from retention and activation branches
        run: |
          RELEASE_NOTES="## Changes in this release\n\n"

          # Check retention branch
          RETENTION_COMMITS=$(git log --oneline --no-merges $(git merge-base origin/main origin/release-retention/daily/$TODAY)..origin/release-retention/daily/$TODAY)
          if [[ ! -z "$RETENTION_COMMITS" ]]; then
            RELEASE_NOTES+="### Retention\n$RETENTION_COMMITS\n\n"
          fi

          # Check activation branch
          ACTIVATION_COMMITS=$(git log --oneline --no-merges $(git merge-base origin/main origin/release-activation/daily/$TODAY)..origin/release-activation/daily/$TODAY)
          if [[ ! -z "$ACTIVATION_COMMITS" ]]; then
            RELEASE_NOTES+="### Activation\n$ACTIVATION_COMMITS\n\n"
          fi

          # Save release notes to a file
          echo -e "$RELEASE_NOTES" > RELEASE_NOTES.md

      - name: Commit and push release notes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add RELEASE_NOTES.md
          git commit -m "Update release notes for $TODAY" || echo "No changes to commit"
          git push || echo "No changes to push"
